[default]
src = 'src'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@opengsn/=node_modules/@opengsn/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config